alias e="explorer.exe ."
alias q="wsl.exe --shutdown"

alias l="ls -alh"
alias r="sudo apt autoremove -y"
alias cd..="cd .."
alias cd2="cd ../.."
alias cd3="cd ../../.."
alias cls="clear"
alias gc="git clone"
alias vi="nvim"
alias nv="nvim"
alias lg="lazygit"
