alias e="explorer.exe ."
alias q="wsl.exe --shutdown"

alias f='cd $(find . -type d | fzf --preview "ls {}")'
alias c="cd .."
alias l="ls -alh"
alias r="sudo apt autoremove -y"
alias u="sudo apt update && sudo apt upgrade"
alias cls="clear"
alias gc="git clone"
alias nv="nvim"
alias lg="lazygit"
alias fd="fdfind"
alias bat="batcat"
alias j8="sudo update-java-alternatives --set /usr/lib/jvm/java-1.8.0-openjdk-amd64"
alias j21="sudo update-java-alternatives --set /usr/lib/jvm/java-1.21.0-openjdk-amd64"
alias gn="git add . && git commit -m "note" && git push"
alias gf="git add . && git commit -m "fix" && git push"
