alias e="explorer.exe ."
alias q="wsl.exe --shutdown"

alias f='cd $(find . -type d | fzf --preview "ls {}")'
alias c="cd .."
alias l="ls -alh"
alias r="sudo apt autoremove -y"
alias u="sudo apt update && sudo apt upgrade"
alias cls="clear"
alias gc="git clone"
alias nv="nvim"
alias vi="nvim"
alias lg="lazygit"
alias g="git add . && git co -m "fix" && git push"
alias fd="fdfind"
