#!/bin/sh

# swaps escape and capslock, fixes broken y key

sudo ln -sf ~/dotfiles/setkeycodes.service /etc/systemd/system/
sudo systemctl start setkeycodes.service
sudo systemctl enable setkeycodes.service

