[language-server.rust-analyzer.config]
checkOnSave = { command = "clippy" }

# [[language]]
# name = "cpp"
# auto-format = true

# [[language]]
# name = "c"
# auto-format = true

[[language]]
name = "java"
# language-servers = []

[language-server.quick-lint-js]
command = "quick-lint-js"
args = ["--lsp-server"]

[[language]]
name = "javascript"
language-servers = ["quick-lint-js", "typescript-language-server"]
auto-format = false

[[language]]
name = "go"
formatter = { command = "goimports" }
