[language-server.clangd]
command = "clangd-22"
args = ["--header-insertion=never"]

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }
# auto-format = true

[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }
# auto-format = true

[[language]]
name = "java"
indent = { tab-width = 4, unit = "    " }
language-servers = []

[language-server.quick-lint-js]
command = "quick-lint-js"
args = ["--lsp-server"]

# language-servers = ["quick-lint-js", "typescript-language-server"]
[[language]]
name = "javascript"
language-servers = ["tsc"]

[[language]]
name = "typescript"
language-servers = ["tsc"]

[language-server.tsc]
command = "tsc"
args = ["--lsp", "--stdio"]

[[language]]
name = "go"
formatter = { command = "goimports" }
