[language-server.rust-analyzer.config]
checkOnSave = { command = "clippy" }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }
# auto-format = true

[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }
# auto-format = true

[[language]]
name = "java"
indent = { tab-width = 4, unit = "    " }
language-servers = []

[language-server.quick-lint-js]
command = "quick-lint-js"
args = ["--lsp-server"]

[[language]]
name = "javascript"
language-servers = ["quick-lint-js", "typescript-language-server"]
auto-format = false

[[language]]
name = "go"
formatter = { command = "goimports" }
